### ISSUE TITLE
parsing utf-8 encoding xml string

### ISSUE THREAD

**Issue by xbinxu** [gniquil/sweet_xml#3]
add scan option to xmerl_scan, otherwise it will raise exception when xml doc contains utf-8 characters:
     :xmerl_scan.string(doc, [encoding: 'iso-10646-utf-1'])

**Comment by gniquil** [comment]
@xbinxu this should be fixed now.

**Comment by xbinxu** [comment]
@gniquil Yeah, it's fixed, thank you!
